#!/bin/bash
#
# Albums in your Bandcamp online collection
# that are missing from your local collection.

# Set Bandcamp username here or in $HOME/.config/calliope/calliope.conf
BANDCAMP_USER=

MPPCONF="${HOME}/.config/mpprc"
[ -f "${MPPCONF}" ] && . "${MPPCONF}"

if [ "${BANDCAMP_USER}" ]
then
  ONLINE_ALBUMS="cpe bandcamp --user ${BANDCAMP_USER} collection"
else
  ONLINE_ALBUMS="cpe bandcamp collection"
fi

#LOCAL_ALBUMS="cpe tracker albums"
LOCAL_ALBUMS="cpe beets albums"

[ -f ${HOME}/.venv/bin/activate ] && source ${HOME}/.venv/bin/activate

cpe diff --scope=album <($ONLINE_ALBUMS | cpe musicbrainz annotate -) <($LOCAL_ALBUMS)
