#!/usr/bin/env python3
# Calliope
# Copyright (C) 2017  Sam Thursfield <sam@afuera.me.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Calliope is a set of tools for processing playlists.

This module is a wrapper script for launching Calliope from the path
where it was installed.

"""

import click

import runpy
import sys

PYTHON_SITE_PACKAGES_DIR = "/usr/lib/python3.10/site-packages/"

sys.path.insert(1, PYTHON_SITE_PACKAGES_DIR)

runpy.run_module("calliope")
