#!/bin/sh
# shellcheck disable=SC2016

get_flexible_fields () {
    beet fields \
        | sed -n "s/^  *//; ${1:-/flexible attributes/,\$p}" \
        | sed -e '/:$/d' \
        | grep -Evx 'alt\..*|singleton|last_import|alt\.|art_source|data_source|totaltracks|track|track_alt' \
        | sort -u
}

usage() {
    echo >&2 "${0##*/} [options]"
    echo >&2
    echo >&2 "Options:"
    echo >&2 "  -a  Album fields only"
    echo >&2 "  -i  Item fields only"
    exit 2
}

album=0
item=0
while getopts aih opt; do
    case "$opt" in
        a)
            album=1
            ;;
        i)
            item=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $album -eq 1 ]; then
    get_flexible_fields '/^Album flexible attributes/,$p'
elif [ $item -eq 1 ]; then
    get_flexible_fields "/^Item flexible attributes/,/flexible attributes/p"
else
    get_flexible_fields
fi
