#!/bin/sh

run_beet() {
    echo >&2 "> beet $*"
    command beet "$@"
}

(
    for cmd in empty-artist empty-album book-not-audiobook unknown-source excess-tracks negative-missing; do
        run_beet "$cmd" "$@" | sed -e "s#^#Warning: $cmd: #"
    done
    run_beet ls -a genre:soundtrack ^albumtypes:soundtrack ^albumtype:soundtrack "$@"
    run_beet ls -a albumtypes:soundtrack ^avmedia::.
    run_beet ls -a albumtype::. albumtypes::'^$' "$@"
    run_beet ls -a needs_album_genre:1 "$@"
) | python3 -c "import sys; d=sys.stdin.read(); print(d); sys.exit(bool(d))" >&2
