#!/bin/sh

dbfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
diskfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$dbfile" "$diskfile"' EXIT INT TERM

export LC_ALL=C

library="$PWD/Library"

beet ls -f '$path' \
    | sort -f >"$dbfile"
find -L "$library" \( -type f -o -type l \) -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) \
    | sort -f >"$diskfile"
touch "$diskfile"
comm -i13 "$dbfile" "$diskfile"
