#!/bin/sh
# shellcheck disable=SC2016

set -e

if [ $# -eq 0 ]; then
    echo >&2 'Usage: remove-album QUERY [..]'
    exit 1
fi

remove_dest="$(beet get-config-path directory)/../Removed"

librarypath="$(cd "$(beet get-config-path directory)" && pwd -P)"
album_flexible_fields="$(beet-flexible-fields -a | xargs | tr ' ' ',')"
item_flexible_fields="$(beet-flexible-fields -i | xargs | tr ' ' ',')"

albums="$(beet ls -f '$id' -a "$@" | xargs)"

for album_id in $albums; do
    beet ls -a id:"$album_id"

    # Ensure paths in library are current
    beet mv -a id:"$album_id"
    # Move the files to Removed
    beet mv -tae -d "$remove_dest" id:"$album_id"
    find "$(beet ls -ap id:"$album_id" | sed -e "s#$librarypath/#$remove_dest/#")" -type f

    # Export flexible fields
    path="$(beet ls -f '$path' -a "id:$album_id")"
    relpath="$(relpath "$path" "$librarypath")"
    destdir="$remove_dest/$relpath"
    if [ -d "$destdir" ]; then
        echo >&2 "Exporting album fields"
        beet export -l -i "$album_flexible_fields" -a "id:$album_id" | jq . >"$destdir/album.json"
        echo >&2 "Exporting album item fields"
        beet export -l -i "path,$item_flexible_fields" "album_id:$album_id" | jq . >"$destdir/items.json"
    fi

    # Remove the files from the db
    beet rm -ad "id:$album_id"
done
