#!/bin/sh

set -e

abspath() {
    # Return an absolute path for the specified argument
    _path="$1"
    if [ -n "${_path##/*}" ]; then
        _path="${2:-$(pwd -P)}/$1"
    fi
    echo "$_path"
}

library_dir="$(beet get-config-path directory)"
dap_dir="$(beet get-config alternatives.dap.directory)"
if [ -z "$dap_dir" ]; then
    echo >&2 "Error looking up alternatives.dap.directory in beets config"
    exit 1
fi
dap_dir="$(abspath "$dap_dir" "$library_dir")"
if [ -z "$dap_dir" ]; then
    exit 1
fi

if ! [ -e /Volumes/DAP ]; then
    echo >&2 "Error locating DAP, please ensure it's mounted."
    exit 3
fi

rsync -avLP --exclude .Trashes --exclude .fseventsd --exclude .DS_Store --exclude ._\* --exclude .Spotlight-V100 --exclude .git --delete "$@" "$dap_dir/" "$library_dir/../Manual Additions/" /Volumes/DAP/
