#!/bin/bash

sudo rm -rf dist releases
make clean
make distclean

rm -f aclocal.m4 \
      compile \
      config.guess \
      config.h.in \
      config.sub \
      configure \
      depcomp \
      install-sh \
      ltmain.sh \
      Makefile.in \
      missing

rm -f doc/Makefile.in \
      m4/libtool.m4 \
      m4/lt~obsolete.m4 \
      m4/ltoptions.m4 \
      m4/ltsugar.m4 \
      m4/ltversion.m4 \
      man/Makefile.in \
      src/Makefile.in

rm -rf src/curses/.deps \
       src/.deps \
       src/screens/.deps \
       src/utility/.deps \
       autom4te.cache
