#!/bin/bash

sudo rm -rf dist releases blissify bliss-analyze

cd essentia
python3 waf distclean
rm -f doc/sphinxdoc/Makefile
rm -f src/3rdparty/kiss_fft130/Makefile
rm -f src/3rdparty/kiss_fft130/test/Makefile
rm -f src/3rdparty/kiss_fft130/tools/Makefile
rm -f src/algorithms/essentia_algorithms_reg.cpp
rm -f src/version.h
rm -f test/3rdparty/gtest-1.6.0/src/gtest-all.o
rm -rf test/audio
rm -rf test/models
rm -rf utils/__pycache__
cd ..

for proj in mpcplus mppcava
do
  cd ${proj}
  [ -f Makefile ] && {
    make clean
    make distclean
  }

  rm -f aclocal.m4 \
      compile \
      config.guess \
      config.h.in \
      config.sub \
      config.log \
      ar-lib \
      configure \
      depcomp \
      install-sh \
      ltmain.sh \
      Makefile.in \
      missing

  rm -f doc/Makefile.in \
      m4/libtool.m4 \
      m4/lt~obsolete.m4 \
      m4/ltoptions.m4 \
      m4/ltsugar.m4 \
      m4/ltversion.m4 \
      man/Makefile.in \
      src/Makefile.in

  rm -rf src/curses/.deps \
       src/.deps \
       src/screens/.deps \
       src/utility/.deps \
       .deps \
       input/.deps \
       output/.deps \
       autom4te.cache
  cd ..
done

rm -f mppcava/version mpcplus/config.h
[ -d mppcava/m4 ] && rmdir mppcava/m4
