#!/bin/bash

[ -f VERSION ] || {
    echo "VERSION file missing. Exiting."
    exit 1
}
. ./VERSION

usage() {
    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
    printf "\nWhere:"
    printf "\n\t-c indicates clean first"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-p indicates create package first"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

CLEAN=
DRAFT=
PACKAGE=
while getopts "cdpu" flag; do
    case $flag in
        c)
            CLEAN=1
            ;;
        d)
            DRAFT="--draft"
            ;;
        p)
            PACKAGE=1
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$CLEAN" ] && ./clean
[ "$PACKAGE" ] && ./mkdeb

ANNO="MusicPlayerPlus Version ${VERSION} Release ${RELEASE}"
gittag v${VERSION}r${RELEASE} ${ANNO}

echo "Copy RPM to releases/${VERSION}"

read -p "Press Enter to continue" answer

echo "Creating release for version ${VERSION} release ${RELEASE}"

gh release create v${VERSION}r${RELEASE} ${DRAFT} \
                  --notes-file pkg/release.md \
                  ./releases/${VERSION}/*

git fetch --tags origin
