#!/bin/sh
# shellcheck disable=SC2016

if [ -n "$BEETS_SKIP_HOOKS" ]; then
    exit 0
fi

if [ -n "$(beet ls last_import:1)" ]; then
    beet ls -a -f '$path' last_import:1
    beet ls -f '$path' last_import:1 album_id:^

    if [ -n "$(beet ls last_import:1 "artpath:^")" ]; then
        echo >&2 "Extracting any embedded album art if needed"
        beet extractart -a last_import:1 "artpath:^" 2>&1
    fi

    if [ -n "$(beet ls -a last_import:1 comments::.)" ]; then
        echo >&2 "Exporting album comments to comments.txt in album folder"
        beet-export-album-comments last_import:1
    fi

    echo >&2 "Checking for red flags"
    beet-check-sanity last_import:1

    if [ -z "${BEETS_SKIP_IMPORT_PAR2:-}" ]; then
        echo >&2 "Generating par2 files"
        beet -p musicintegrity par2create last_import:1 2>/dev/null
    fi
fi
