# Output of 'beet config'
#

directory: ~/Music
library: ~/.config/beets/musiclibrary.db

lyrics:
    bing_lang_from: []
    auto: no
    sources: tekstowo
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no

import:
    copy: yes
    move: yes
    write: yes
    incremental: yes
    incremental_skip_later: yes
    quiet: no
    quiet_fallback: asis
    resume: yes
    from_scratch: no
    default_action: apply
    detail: yes
    non_rec_action: ask
    duplicate_action: skip
    group_albums: no
    autotag: yes
    bell: no
    log: ~/.config/beets/logs/import.log

plugins:
#   - acousticbrainz
    - albumtypes
    - bandcamp
    - describe
    - duplicates
    - edit
    - fetchart
    - fromfilename
    - hook
    - importadded
    - info
    - lyrics
    - lastgenre
    - missing
    - mbsync
    - mpdstats
    - play
    - playlist
    - smartplaylist
    - mpdupdate
    - unimported
    - xtractor
    - yearfixer

#acousticbrainz:
#   auto: no
#   force: no
#   base_url: https://acousticbrainz.org
#   tags: []

albumtypes:
    types:
    -   album: ''
    -   ep: EP
    -   single: Single
    -   soundtrack: OST
    -   live: Live
    -   compilation: Anthology
    -   remix: Remix
    ignore_va: compilation
    bracket: '[]'

bandcamp:
    include_digital_only_tracks: yes
    search_max: 2
    art: no
    comments_separator: '

        ---

        '
    exclude_extra_fields: [comments]
    genre:
        capitalize: no
        maximum: 0
        always_include: []
        mode: progressive

duplicates:
    album: no
    checksum: ffmpeg -i {file} -f crc -
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''

fetchart:
    auto: no
    cautious: no
    enforce_ratio: yes
    minwidth: 256
    maxwidth: 3000
    sources:
    - filesystem
    - coverart
    - albumart
    - wikipedia
    store_source: yes
    quality: 0
    max_filesize: 0
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    high_resolution: no
    deinterlace: no
    cover_format:

mpdstats:
    host: localhost
    port: 6600
    rating: yes
    rating_mix: 0.75

lastgenre:
    auto: no
    canonical: ~/.config/beets/genres/genres-tree.yaml
    count: 1
    fallback: Unknown
    force: no
    min_weight: 10
    prefer_specific: yes
    source: track
    separator: ', '
    whitelist: ~/.config/beets/genres/genres.txt
    title_case: yes

play:
    command: /usr/share/musicplayerplus/scripts/mpcplay.sh $args
    relative_to: ~/Music
    raw: yes
    warning_threshold: 500
    use_folders: no
    bom: no

playlist:
    auto: yes
    relative_to: ~/Music
    playlist_dir: ~/Music/Playlists
    forward_slash: no

smartplaylist:
    auto: no
    relative_to: ~/Music
    playlist_dir: ~/Music/Playlists
    forward_slash: no
    playlists:
    -   name: rating.m3u
        query: rating:0.4..1.0
    -   name: 1940s.m3u
        query: original_year:1940..1949
    -   name: 1950s.m3u
        query: original_year:1950..1959
    -   name: 1960s.m3u
        query: original_year:1960..1969
    -   name: 1970s.m3u
        query: original_year:1970..1979
    -   name: 1980s.m3u
        query: original_year:1980..1989
    -   name: 1990s.m3u
        query: original_year:1990..1999
    -   name: 2000s.m3u
        query: original_year:2000..2009
    -   name: 2010s.m3u
        query: original_year:2010..2019
    -   name: 2020s.m3u
        query: original_year:2020..2029
    -   name: ReleasedIn$original_year.m3u
        query: original_year::195(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::196(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::197(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::198(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::199(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::200(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::201(0|1|2|3|4|5|6|7|8|9)
    -   name: ReleasedIn$original_year.m3u
        query: original_year::202(0|1|2)
    prefix: REDACTED
    urlencode: no

mpd:
    host: localhost
    port: 6600
    rating: yes
    rating_mix: 0.75
    music_directory: ~/Music
    strip_path: ''
    password: REDACTED

musicbrainz:
    extra_tags:
    - year
    - catalognum
    - country
    - media
    - label

match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.25
    max_rec:
        unmatched_tracks: low
        missing_tracks: strong
    distance_weights:
        album: 6.0
        artist: 7.0
        totaltracks: 4.0
        missing_tracks: 1.0
        unmatched_tracks: 10.0
    preferred:
        countries: [US, XW, GB|UK]
        media: [Digital Media|File, CD]
    ignored_media:
    - DVD
    - DVD-Video
    - Blu-ray
    - HD-DVD
    - VCD
    - SVCD
    - UMD
    - VHS

#paths:
#    default: '%if{$albumartist,%title{$albumartist},%if{$artist,%title{$artist},Unknown Artist}}/[%if{$original_year,$original_year,%if{$year,$year,0000}}] %if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title'
#    singleton: '%if{$albumartist,%title{$albumartist},%if{$artist,%title{$artist},Unknown Artist}}/[%if{$original_year,$original_year,%if{$year,$year,0000}}] %if{$album,$album%aunique{},Unknown Album}/$track - $title'
#    comp: Compilations/[%if{$original_year,$original_year,%if{$year,$year,0000}}] %if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $artist - $title
#    albumtype:soundtrack: Soundtracks/[%if{$original_year,$original_year,%if{$year,$year,0000}}] %if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title
paths:
    default: '%if{$albumartist,%title{$albumartist},%if{$artist,%title{$artist},Unknown Artist}}/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title'
    singleton: '%if{$albumartist,%title{$albumartist},%if{$artist,%title{$artist},Unknown Artist}}/%if{$album,$album%aunique{},Unknown Album}/$track - $title'
    comp: Compilations/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $artist - $title
    albumtype:soundtrack: Soundtracks/%if{$album,$album%aunique{},Unknown Album}%if{$atypes, $atypes}/$track - $title

ignore:
- .DS_Store
- .*
- '*~'
- System Volume Information
- lost+found

importadded:
    preserve_mtimes: yes
    preserve_write_mtimes: yes

threaded: yes

unimported:
    ignore_extensions: jpg png
    ignore_subdirectories: data tmp

xtractor:
    auto: no
    dry-run: no
    write: yes
    threads: 2
    force: no
    quiet: no
    keep_output: yes
    keep_profiles: no
    output_path: ~/.config/beets/xtraction_data
    essentia_extractor: /usr/bin/essentia_streaming_extractor_music
    extractor_profile:
        outputFormat: json
        outputFrames: 0
        lowlevel:
            frameSize: 2048
            hopSize: 1024
        chromaprint:
            compute: 0
        highlevel:
            compute: 1
            svm_models:
            - /usr/share/mpplus-essentia/svm_models/danceability.history
            - /usr/share/mpplus-essentia/svm_models/gender.history
            - /usr/share/mpplus-essentia/svm_models/genre_rosamerica.history
            - /usr/share/mpplus-essentia/svm_models/ismir04_rhythm.history
            - /usr/share/mpplus-essentia/svm_models/mood_acoustic.history
            - /usr/share/mpplus-essentia/svm_models/mood_aggressive.history
            - /usr/share/mpplus-essentia/svm_models/mood_electronic.history
            - /usr/share/mpplus-essentia/svm_models/mood_happy.history
            - /usr/share/mpplus-essentia/svm_models/mood_party.history
            - /usr/share/mpplus-essentia/svm_models/mood_relaxed.history
            - /usr/share/mpplus-essentia/svm_models/mood_sad.history
            - /usr/share/mpplus-essentia/svm_models/moods_mirex.history
            - /usr/share/mpplus-essentia/svm_models/timbre.history
            - /usr/share/mpplus-essentia/svm_models/tonal_atonal.history
            - /usr/share/mpplus-essentia/svm_models/voice_instrumental.history
    low_level_targets:
        bpm:
            path: rhythm.bpm
            type: integer
            required: yes
        danceability:
            path: rhythm.danceability
            type: float
        beats_count:
            path: rhythm.beats_count
            type: integer
#       average_loudness:
#           path: lowlevel.average_loudness
#           type: float
#           required: yes
        initial_key:
            path: tonal.initial_key
            type: string
    high_level_targets:
        key_key:
            path: tonal.key_edma.key
            type: string
        key_scale:
            path: tonal.key_edma.scale
            type: string
        chords_key:
            path: tonal.chords_key
            type: string
        chords_scale:
            path: tonal.chords_scale
            type: string
        replay_gain:
            path: metadata.audio_properties.replay_gain
            type: float
        integrated_loudness:
            path: lowlevel.loudness_ebu128.integrated
            type: float
        loudness_range:
            path: lowlevel.loudness_ebu128.loudness_range
            type: float
        timbre:
            path: highlevel.timbre.value
            type: string
            required: yes
        danceable:
            path: highlevel.danceability.value
            type: string
            required: yes
        is_danceable:
            path: highlevel.danceability.all.danceable
            type: float
        genre_rosamerica:
            path: highlevel.genre_rosamerica.value
            type: string
            required: yes
        mood_acoustic:
            path: highlevel.mood_acoustic.value
            type: string
            required: yes
        mood_aggressive:
            path: highlevel.mood_aggressive.value
            type: string
            required: yes
        mood_electronic:
            path: highlevel.mood_electronic.value
            type: string
            required: yes
        mood_happy:
            path: highlevel.mood_happy.value
            type: string
            required: yes
        mood_sad:
            path: highlevel.mood_sad.value
            type: string
            required: yes
        mood_party:
            path: highlevel.mood_party.value
            type: string
            required: yes
        mood_relaxed:
            path: highlevel.mood_relaxed.value
            type: string
            required: yes
        gender:
            path: highlevel.gender.value
            type: string
            required: yes
        is_male:
            path: highlevel.gender.all.male
            type: float
        is_female:
            path: highlevel.gender.all.female
            type: float
        voice_instrumental:
            path: highlevel.voice_instrumental.value
            type: string
            required: yes
        is_voice:
            path: highlevel.voice_instrumental.all.voice
            type: float
        is_instrumental:
            path: highlevel.voice_instrumental.all.instrumental
            type: float
        mood_mirex:
            path: highlevel.moods_mirex.value
            type: string
            required: yes
        mood_mirex_cluster_1:
            path: highlevel.moods_mirex.all.Cluster1
            type: float
        mood_mirex_cluster_2:
            path: highlevel.moods_mirex.all.Cluster2
            type: float
        mood_mirex_cluster_3:
            path: highlevel.moods_mirex.all.Cluster3
            type: float
        mood_mirex_cluster_4:
            path: highlevel.moods_mirex.all.Cluster4
            type: float
        mood_mirex_cluster_5:
            path: highlevel.moods_mirex.all.Cluster5
            type: float

yearfixer:
    force: yes
    auto: no

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

hook:
    hooks: [{event: import_begin, command: /usr/share/musicplayerplus/scripts/beet_log.sh Import begin}, {event: import, command: /usr/share/musicplayerplus/scripts/beet_log.sh Import end}]

edit:
    albumfields: album albumartist
    itemfields: track title artist album
    ignore_fields: id path

missing:
    count: no
    total: no
    album: no

describe:
    auto: no