#!/bin/bash
export FIFO_UEBERZUG="/tmp/mpd-ueberzug-${PPID}"

cleanup() {
    rm "$FIFO_UEBERZUG" 2>/dev/null
    rm /tmp/mpd_cover.jpg 2>/dev/null
    pkill -P $$ 2>/dev/null
    pkill mpcplus_cover_art.sh
}

[ -f ${HOME}/.venv/bin/activate ] && source ${HOME}/.venv/bin/activate

USE_MPCPLUS=1
USE_NCMPCPP=
CLIENT_COMM="mpcplus"
while getopts "c:" flag; do
    case $flag in
        c)
            CLIENT_COMM="$OPTARG"
            client_name=`echo "${CLIENT_COMM}" | awk ' { print $1 } '`
            client_name=`basename ${client_name}`
            [ "${client_name}" == "mpcplus" ] || USE_MPCPLUS=
            [ "${client_name}" == "ncmpcpp" ] && USE_NCMPCPP=1
            ;;
    esac
done

pkill -P $$ 2>/dev/null
rm "$FIFO_UEBERZUG" 2>/dev/null
mkfifo "$FIFO_UEBERZUG" >/dev/null
trap cleanup EXIT 2>/dev/null
tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser simple >/dev/null 2>&1 &

if [ "${USE_MPCPLUS}" ]
then
  ${CLIENT_COMM} --config="${HOME}/.config/mpcplus/ueberzug/config"
else
  if [ "${USE_NCMPCPP}" ]
  then
    ${CLIENT_COMM} --config="${HOME}/.config/mpcplus/ueberzug/config-ncmpcpp"
  else
    ${CLIENT_COMM}
  fi
fi
cleanup
