#!/bin/bash

set -euo pipefail

topdir="$(cd "$(dirname "$0")/.." && pwd -P)"

case "${OSTYPE:-}" in
    darwin*)
        if command -v gcp >/dev/null 2>&1; then
            copy () {
                gcp -al "$@"
            }
        else
            copy () {
                cp -a "$@"
            }
        fi
        ;;
    *)
        copy () {
            cp -al "$@"
        }
esac

git init
copy "$topdir"/.git/objects/. .git/objects/
git remote add origin "$topdir"
git fetch --tags origin
git fetch origin
git checkout -f -b main origin/main
git remote set-url origin "$(cd "$topdir" && git config remote.origin.url)"
git fetch origin || :

workspace="$(pwd -P)"
( cd "$topdir" && git ls -mo ) \
    | while read -r fn; do
        if [ "$topdir/$fn" = "$workspace/" ]; then
            continue
        fi
        mkdir -p "$(dirname "$fn")"
        case "$fn" in
            */)
                cp -a "$topdir/$fn." "$fn"
                ;;
            *)
                cp -a "$topdir/$fn" "$fn"
                ;;
        esac
    done

if command -v yq >/dev/null 2>&1; then
    {
        echo
        echo "plugins:"
        ( cd "$topdir" && beet config ) | yq e .plugins - | sed -e 's/^/  /'
        echo
        echo '# Local'
        echo '  - nowrite'
    } >>config.d/local.yaml
else
    sed -i.bak -e '/^ *# - nowrite/s/# //' config.yaml
    rm -f config.yaml.bak
fi
mkdir -p Library
cp -a "$topdir/Library/library.db" Library/
cp -a "$topdir/Library/Playlists/." Library/Playlists/
../script/init

direnv allow

if [ "${VISUAL:-${EDITOR:-vim}}" = code ]; then
    code .
fi
