#!/bin/sh

PATH="$(dirname "$0"):$PATH"

for url in https://github.com/beetbox/beets \
           https://github.com/snejus/beetcamp \
           https://github.com/kergoth/beets-kergoth \
           https://github.com/edk0/beets-join-albums \
           https://github.com/kergoth/beets-alternatives \
           https://github.com/adammillerio/beets-copyartifacts \
           https://github.com/geigerzaehler/beets-check \
           https://github.com/adamjakab/BeetsPluginXtractor \
           https://github.com/adamjakab/BeetsPluginYearFixer \
           https://github.com/phirestalker/beets-musicintegrity \
           https://github.com/tandy-1000/whatlastgenre@patch-1; do

    case "$url" in
        *copyartifacts*)
            branch=devel
            ;;
        *)
            branch=master
            ;;
    esac

    spec="git+$url"
    if [ -d src ]; then
        name="$(basename "${url%@*}")"
        if [ -d "src/$name" ]; then
        ( cd "src/$name" && git checkout "$branch" && git pull )
        spec="src/$name"
        fi
    else
        if [ "$branch" != master ]; then
            spec="$spec@$branch"
        fi
    fi

    set -- "$@" "$spec"
done

beets="$1"
shift
pipx install -f "$beets"
pipx inject beets "$@" requests discogs-client pyacoustid beets-bandcamp beets-noimport requests_oauthlib pylast beautifulsoup4
