language: python
python:
- 3.5
- 3.6
- 3.7
cache:
  pip: true

install:
- python -m pip install coverage flake8 flake8-docstrings
- python setup.py install

before_script:
- flake8 --statistics .
script:
- coverage run setup.py test
- python setup.py build sdist bdist_wheel
after_script:
- coverage report -m --include "beetsplug/*","tests/*","setup.py"

# Deployment
before_deploy:
  - python -m pip install -U twine setuptools wheel
  - twine --version
deploy:
  # Deploy to PyPI
- provider: script
  script: twine upload  --skip-existing dist/*
  skip_cleanup: true
  on:
    branch: master
    repo: Holzhaus/beets-extrafiles
    tags: true
  # Deploy to Github Releases
- provider: releases
  api_key:
    secure: VjUTO4tdkWEYpip7ZA31fQl2cP4JiGdfzV/R5S9RTOjuYZAg8lmZunf6osC7tH45uX7yCROoz+G19MxwIZvJLir+TA5HoBm1GHcYVRiIG0QKHUSB+2zrdwWfSribC6Uemg9b1197iZcXhGtxpzyQEZFFDecF1jXStDDUtFpfyHACbQ2lcPvIL2eb0m12KAjGl1hQtkvRmE9EXPkkisP9gfbgqFbiuvUo2s75MGRV3rE2YzX8cWIUlrcTJtqT2bGW8svjx66nivf+6+0APTJEt2C+04oi12QN815K4/QWMNppqS/5JlzDFYlsaT+Wx8TNKbNCjbm3+fVKO/XO0njgMbzponefnNM/fBf0KQMg7Y52SwyttQbNUV3uX7Q+Tp5yLIx/nRQFJ83uDbf87HT9Ab85mGJl3xPa7FQZehAnyeAMOn5t3sSsGEPL4VWpifYxLttE4AClDZ9PrVj0Z8VZOHqVKmL0ct1yUbBG5SWJ1VojXbCB8CoF4V1eEOJP7IIk1NROSq+Ae0TEuv0ullYmV6SMUrDsny/2YT/TPOIxKKUqc0QrBq3zQwazyOfZ61rzka55ShtIvINJeYtqUfBiicuBSrk8e0/TKvkdHp6Vbel/oiJvWmWexKHdfw/fBq6x5YEd/oWSYeIzhOVHsA/ZJMxzuHnx4+XmTchkqmg8ZLs=
  name: "$TRAVIS_TAG"
  body: "Release $TRAVIS_TAG"
  draft: false
  skip_cleanup: true
  file_glob: true
  file: dist/*
  overwrite: true
  on:
    branch: master
    repo: Holzhaus/beets-extrafiles
    tags: true

# Base System
dist: bionic
addons:
  apt:
    sources:
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
    packages:
    - bash-completion
    - gir1.2-gst-plugins-base-1.0
    - gir1.2-gstreamer-1.0
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - imagemagick
    - python-gi
    - python-gst-1.0
    - python3-gi
    - python3-gst-1.0
    - unrar
